import React,{useState} from 'react';
import './Projects.css';

const projects=[
 {title:'RDT Ticketing Application',category:'Full Stack',icon:'🎟️',description:'A ticketing platform for Rice Dance Theatre with show listings, seat availability, and ticket management.',technologies:['MongoDB','JavaScript','Node.js'],link:'https://github.com/rice-apps/rdt-ticketing/tree/main/client'},
 {title:'FDA Adverse Events',category:'Data Science',icon:'🧪',description:'Analyzed consumer-product safety reports to identify risk patterns in FDA adverse-event data.',technologies:['Python','Pandas','Scikit-learn'],link:'https://devpost.com/software/analysing-reported-fda-adverse-events-of-consumer-products?ref_content=user-portfolio&ref_feature=in_progress'},
 {title:'Concurrent Web Proxy',category:'Systems',icon:'🌐',description:'A multithreaded web proxy with concurrent request handling and traffic logging.',technologies:['C','Networking','Concurrency'],link:'https://github.com/meaghanramlakhan8/concurrent-web-proxy'},
 {title:'Locality-Sensitive Hashing',category:'Machine Learning',icon:'🔎',description:'Benchmarked LSH methods for approximate nearest-neighbor search across high-dimensional text data.',technologies:['Python','NumPy','Scikit-learn'],link:'https://github.com/meaghanramlakhan8/Locality-Sensitive-Hashing-Analysis-for-Text-Similarity-Search'},
 {title:'OwlDB + M3ssag1n8',category:'Systems',icon:'🦉',description:'A concurrent NoSQL document database powering a real-time messaging application.',technologies:['Go','TypeScript','SSE']},
 {title:'Global Health Disparities',category:'Data Science',icon:'🌍',description:'Investigated how health, economic, and social factors influence life expectancy using WHO and United Nations data.',technologies:['Regression','Statistical Modeling','Data Viz']},
 {title:'Genome Read-Mapping Pipeline',category:'Healthcare Tech',icon:'🧬',description:'Built a bioinformatics pipeline for mapping genomic sequencing reads to a reference genome while evaluating accuracy and computational tradeoffs.',technologies:['Python', 'Cython', 'Bioinformatics','Genome-Scaled Algorithms','Data Pipelines']},
 {title:'CVD Mortality Analysis',category:'Data Science',icon:'🫀',description:'Explored hypertension-related mortality trends across demographic, geographic, and insurance factors.',technologies:['R','ggplot2','SQL']},
];
const filters=['All','Full Stack','Systems','Data Science','Machine Learning','Healthcare Tech'];

export default function Projects(){
 const[active,setActive]=useState('All');
 const[selected,setSelected]=useState(null);
 const visible=active==='All'?projects:projects.filter(project=>project.category===active);
 return <main className="projects-container page-shell">
  <header className="projects-header page-header"><p className="eyebrow">PROJECTS.JSON // {String(projects.length).padStart(2,'0')} OBJECTS</p><h1>Things I’ve built and investigated.</h1><p>Filter through full-stack products, systems work, data investigations, machine learning, and healthcare technology.</p></header>
  <div className="project-filters" role="group" aria-label="Filter projects">{filters.map(filter=><button className={active===filter?'active':''} onClick={()=>setActive(filter)} key={filter}><span>{filter}</span><b>{filter==='All'?projects.length:projects.filter(p=>p.category===filter).length}</b></button>)}</div>
  <div className="projects-grid">{visible.map((project,index)=><article className="project-card" key={project.title}>
   <div className="project-media"><div className="project-glyph" aria-hidden="true"><i/><i/><strong>{project.icon}</strong><small>{project.category}</small></div><span>{String(index+1).padStart(2,'0')} / {project.category}</span></div>
   <div className="project-info"><h2>{project.title}</h2><p>{project.description}</p><div className="tech-list">{project.technologies.map(tech=><span key={tech}>{tech}</span>)}</div><button className="case-button" onClick={()=>setSelected(project)}>Open case study <span>⌘ ↗</span></button>{project.link?<a href={project.link} target="_blank" rel="noreferrer">Inspect project <span>↗</span></a>:<span className="private-label">COURSE PROJECT // PRIVATE REPO</span>}</div>
  </article>)}</div>
  {selected&&<div className="case-modal-backdrop" onMouseDown={()=>setSelected(null)}><section className="case-modal" role="dialog" aria-modal="true" aria-label={`${selected.title} case study`} onMouseDown={e=>e.stopPropagation()}><header><span>CASE_STUDY.MD // {selected.category}</span><button onClick={()=>setSelected(null)} aria-label="Close case study">ESC ×</button></header><div className="case-modal-grid"><div className="modal-visual"><img src={selected.image} alt=""/><div><span>STATUS</span><b>✓ COMPLETE</b></div></div><div className="modal-copy"><p className="eyebrow">TECHNICAL DEEP DIVE</p><h2>{selected.title}</h2><p>{selected.description}</p><div className="case-detail"><span>01 / PROBLEM</span><p>Transform a technically complex workflow into a reliable, usable system with clear data flow and maintainable components.</p></div><div className="case-detail"><span>02 / ENGINEERING</span><p>Designed and implemented the core workflow using {selected.technologies.join(', ')}, balancing correctness, performance, and usability.</p></div><div className="case-detail"><span>03 / RESULT</span><p>Delivered a working {selected.category.toLowerCase()} project with tested functionality and a clear path for iteration.</p></div><div className="tech-list">{selected.technologies.map(tech=><span key={tech}>{tech}</span>)}</div>{selected.link&&<a className="button button-primary" href={selected.link} target="_blank" rel="noreferrer">View source <span>↗</span></a>}</div></div></section></div>}
 </main>
}